package sgp4

import (
	"math"
	"testing"
)

// Reference vectors below were generated by compiling a patched copy of the
// upstream SGP4.cpp (a temporary local patch to satnum parsing only, to
// avoid an unrelated pointer-to-int cast that doesn't compile on 64-bit
// clang -- irrelevant to the propagator math) and calling initl/dscom/
// dpper/dsinit/dspace directly with inputs derived from three real
// SGP4-VER.TLE satellites, chosen to cover all three irez classifications:
//
//	irez0_23333: satnum 23333 (WIND), non-resonant deep-space
//	irez1_26900: satnum 26900 (INTELSAT-902-ish GEO), 24h resonance
//	irez2_08195: satnum 08195 (MOLNIYA 2-14), 12h resonance
//
// Full end-to-end propagation of all three (and 30 others) is separately
// validated in regression_test.go against independently-produced golden
// output files; these tests isolate the internal deep-space/init functions
// specifically, with a tight tolerance appropriate for a direct one-shot
// comparison against full-precision reference doubles (no accumulated
// integration drift at this level, unlike the end-to-end regression suite).
const fixtureTol = 1e-9

func almostEqual(t *testing.T, label string, got, want float64) {
	t.Helper()
	if math.Abs(got-want) > fixtureTol*math.Max(1.0, math.Abs(want)) {
		t.Errorf("%s: got %.17g, want %.17g (diff %.3g)", label, got, want, got-want)
	}
}

func TestInitl(t *testing.T) {
	cases := []struct {
		name                                              string
		xke, j2, ecco, epoch, inclo, noKozai              float64
		wantMethod                                        byte
		wantAinv, wantAo, wantCon41, wantCon42            float64
		wantCosio, wantCosio2, wantEccsq, wantOmeosq      float64
		wantPosq, wantRp, wantRteosq, wantSinio, wantGsto float64
		wantNoUnkozai                                     float64
	}{
		{
			name: "irez0_23333", xke: 0.074366916133173422, j2: 0.001082616,
			ecco: 0.97282979999999997, epoch: 16376.499999990221,
			inclo: 0.50176470665584982, noKozai: 0.00031893671148723211,
			wantMethod: 'n',
			wantAinv:   0.026395663781406287, wantAo: 37.885010518448226,
			wantCon41: 1.3059935719020523, wantCon42: -2.8433226198367536,
			wantCosio: 0.87673515041165695, wantCosio2: 0.76866452396735074,
			wantEccsq: 0.94639781976803994, wantOmeosq: 0.053602180231960062,
			wantPosq: 4.1238203145060695, wantRp: 1.0293433127883433,
			wantRteosq: 0.23152144659180079, wantSinio: 0.48097346707760225,
			wantGsto: 3.8492195685660988, wantNoUnkozai: 0.00031891772263956645,
		},
		{
			name: "irez1_26900", xke: 0.074366916133173422, j2: 0.001082616,
			ecco: 0.00033189999999999999, epoch: 20560.745032470208,
			inclo: 0.00028623399732707005, noKozai: 0.0043752719594775955,
			wantMethod: 'n',
			wantAinv:   0.15126534019297194, wantAo: 6.6108997522121182,
			wantCon41: 1.999999754210303, wantCon42: -3.9999995903505052,
			wantCosio: 0.99999995903504968, wantCosio2: 0.99999991807010102,
			wantEccsq: 1.1015760999999999e-07, wantOmeosq: 0.99999988984238997,
			wantPosq: 43.703985905143391, wantRp: 6.6087055945843582,
			wantRteosq: 0.99999994492119348, wantSinio: 0.00028623399341854957,
			wantGsto: 1.9712765253007092, wantNoUnkozai: 0.0043751093799833923,
		},
		{
			name: "irez2_08195", xke: 0.074366916133173422, j2: 0.001082616,
			ecco: 0.68771459999999995, epoch: 20630.332154440228,
			inclo: 1.1197788134700339, noKozai: 0.0087480868880674655,
			wantMethod: 'n',
			wantAinv:   0.24008817584663966, wantAo: 4.1651363982154903,
			wantCon41: -0.43002188663164709, wantCon42: 0.050036477719411859,
			wantCosio: 0.43588152571096384, wantCosio2: 0.18999270445611763,
			wantEccsq: 0.47295137105315993, wantOmeosq: 0.52704862894684013,
			wantPosq: 4.8190322418033098, wantRp: 1.300711286171284,
			wantRteosq: 0.7259811491676903, wantSinio: 0.90000405307080833,
			wantGsto: 0.57418012690401099, wantNoUnkozai: 0.008748547019630239,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			// The 'a' opsmode is inert in initl's current body (the
			// opsmode-conditional branch is dead code upstream -- see
			// initl's doc comment), so any value is fine here.
			r := initl(c.xke, c.j2, c.ecco, c.epoch, c.inclo, c.noKozai, 'a')
			if r.Method != c.wantMethod {
				t.Errorf("Method: got %c, want %c", r.Method, c.wantMethod)
			}
			almostEqual(t, "Ainv", r.Ainv, c.wantAinv)
			almostEqual(t, "Ao", r.Ao, c.wantAo)
			almostEqual(t, "Con41", r.Con41, c.wantCon41)
			almostEqual(t, "Con42", r.Con42, c.wantCon42)
			almostEqual(t, "Cosio", r.Cosio, c.wantCosio)
			almostEqual(t, "Cosio2", r.Cosio2, c.wantCosio2)
			almostEqual(t, "Eccsq", r.Eccsq, c.wantEccsq)
			almostEqual(t, "Omeosq", r.Omeosq, c.wantOmeosq)
			almostEqual(t, "Posq", r.Posq, c.wantPosq)
			almostEqual(t, "Rp", r.Rp, c.wantRp)
			almostEqual(t, "Rteosq", r.Rteosq, c.wantRteosq)
			almostEqual(t, "Sinio", r.Sinio, c.wantSinio)
			almostEqual(t, "Gsto", r.Gsto, c.wantGsto)
			almostEqual(t, "NoUnkozai", r.NoUnkozai, c.wantNoUnkozai)
		})
	}
}
